{{- range .Values.services.pihole }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole-{{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    cozystack.io/ui: "true"
spec:
  chart:
    spec:
      chart: pihole
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: cozy-public
      version: 2.29.1
  interval: 1m0s
  timeout: 5m0s
  values:
    {{- toYaml .values | nindent 4 }}
{{- end }}
