apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-values
  namespace: networking
data:
  values.yaml: |
    DNS1:
      192.168.178.1
    persistentVolumeClaim:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - "pihole.hyrule"
    serviceWeb:
      loadBalancerIP: 192.168.178.201
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 192.168.178.201
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    dnsmasq:
      customDnsEntries:
        - address=/dashboard.hyrule/192.168.178.200
        - address=/grafana.hyrule/192.168.178.200
        - address=/pihole.hyrule/192.168.178.201
