serviceWeb:
  loadBalancerIP: 192.168.178.201
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.178.201
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

admin:
  existingSecret: "changeme"
  password: "changeme"

dnsmasq:
  customDnsEntries:
    - address=/dashboard.hyrule/192.168.178.200
    - address=/grafana.hyrule/192.168.178.200
    - address=/pihole.hyrule/192.168.178.201
