apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tenant-kokiri
  namespace: tenant-root
  labels:
    cozystack.io/ui: "true"
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: cozystack-apps
        namespace: cozy-public
      version: '*'
  interval: 1m0s
  timeout: 5m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    etcd: false
    controlPlane: false
    monitoring: false
    ingress: true
    isolated: false
    seaweedfs: false
    host: "kokiri.hyrule"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tenant-kokiri-services
  namespace: tenant-root
spec:
  chart:
    spec:
      chart: ./charts/staging
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: hyrule-gitops
        namespace: tenant-root
      version: '*'
  interval: 1m0s
  timeout: 5m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    namespace: tenant-kokiri
    services:
      pihole:
      - name: service
        values:
          DNS1:
            192.168.178.1
          persistentVolumeClaim:
            enabled: true
          ingress:
            enabled: true
          serviceWeb:
            loadBalancerIP: 192.168.178.201
            annotations:
              metallb.universe.tf/allow-shared-ip: pihole-svc
            type: LoadBalancer
          serviceDns:
            loadBalancerIP: 192.168.178.201
            annotations:
              metallb.universe.tf/allow-shared-ip: pihole-svc
            type: LoadBalancer
          podDnsConfig:
            enabled: true
            policy: "None"
            nameservers:
            - 127.0.0.1
            - 8.8.8.8
          dnsmasq:
            customDnsEntries:
              - address=/dashboard.hyrule/192.168.178.200
              - address=/grafana.hyrule/192.168.178.200
              - address=/pihole.hyrule/192.168.178.201
      kubernetes:
      - name: service
        # Here you can specify applications to deploy via FluxCD into tenant-cluster
        #fluxSync:
        #  values:
        #    secret:
        #      create: true
        #      data:
        #        password: token-string-here123
        #        username: pat
        #    gitRepository:
        #      spec:
        #        url: https://gitlab.com/example/infra.git
        #        ref:
        #          branch: main
        #    kustomization:
        #      spec:
        #        path: clusters/tenant-example

        values:
          addons:
            certManager:
              enabled: true
            fluxcd:
              enabled: true
            cilium:
              enabled: true
          controlPlane:
            replicas: 2
          nodeGroups:
            md0:
              maxReplicas: 2
              minReplicas: 0
              resources:
                cpu: 2
                memory: 4096Mi
